@extends('layout.portal')

@section('content')
    <div id="main-page" class="wrap-page">
        <nav>
            <div class="wrap-nav clearfix">
                {{-- vue navigation component located --}}
                <app-main-nav-component v-bind="main"></app-main-nav-component>
            </div>
        </nav>
        <section class="section">
            {{-- router view, a vue view component generated by vue router component --}}
            <router-view></router-view>
        </section>
        {{-- footer component --}}
        <app-main-footer-component></app-main-footer-component>
    </div>
    {{-- using laravel mix to generate js file --}}
    <script type="text/javascript" src="{{ mix('/js/main.js') }}"></script>
@endsection
